src/main/java/com/hrbank/dto/binarycontent/BinaryContentCreateRequest.java, src/main/java/com/hrbank/dto/binarycontent/BinaryContentDto.java, src/main/java/com/hrbank/entity/BinaryContent.java, src/main/java/com/hrbank/mapper/BinaryContentMapper.java, src/main/java/com/hrbank/repository/BinaryContentRepository.java, src/main/java/com/hrbank/service/BasicBinaryContentService.java, src/main/java/com/hrbank/service/BinaryContentService.java, src/main/java/com/hrbank/storage/BinaryContentStorage.java
feat/9-binaryContent-create -> main
- 파일 관리 기능을 위한 핵심 도메인 `BinaryContent` 정의
- 파일 저장을 위한 Repository(JpaRepository상속) 생성
- BinaryContentService인터페이스, BasicBinaryContentService클래스 생성
- 파일 저장 기능 구현을 위해 `BasicBinaryContentService`에 `create()`생성
- Closes #9
=> [#9] BinaryContent 엔터티 & 관련 파일 추가 및 파일 셍성 기능 추가

src/main/java/com/hrbank/dto/employeeChangeLog/EmployeeChangeLogSearchRequest.java, src/main/java/com/hrbank/entity/EmployeeChangeLog.java, src/main/java/com/hrbank/entity/EmployeeChangeLogDetail.java, src/main/java/com/hrbank/enums/EmployeeChangeLogType.java, src/main/java/com/hrbank/repository/EmployeeChangeLogRepository.java, src/main/java/com/hrbank/repository/specification/EmployeeChangeLogSpecification.java, src/main/java/com/hrbank/service/EmployeeChangeLogService.java, src/main/java/com/hrbank/service/basic/BasicEmployeeChangeLogService.java
feat/07-employee-log-setup -> main
- 직원 이력 관리 기능을 위한 핵심 도메인 정의
- `EmployeeChangeLog`, `EmployeeChangeLogDetail` 설계
- ID 타입은 프로젝트 전체 일관성을 위해 UUID → Long으로 통일
- 이력 유형 구분을 위한 Enum 정의 (`EmployeeChangeLogType`)
- 이력 저장을 위한 Repository (`JpaSpecificationExecutor` 적용)
- 동적 검색 조건 대응을 위한 Specification 클래스 구성
- 검색 요청 DTO (`EmployeeChangeLogSearchRequest`) 작성
- 기본 조회용 서비스 (`EmployeeChangeLogService`, `Basic~`) 인터페이스 및 구현체 구성
- Closes #7
=> [#7] 직원 이력 관리 도메인 정의 및 검색 기능 기본 구조 구현

build.gradle, src/main/java/com/hrbank/dto/backup/BackupDto.java, src/main/java/com/hrbank/entity/Backup.java, src/main/java/com/hrbank/enums/EmployeeCsvHeader.java, src/main/java/com/hrbank/mapper/BackupMapper.java, src/main/java/com/hrbank/scheduler/BackupScheduler.java, src/main/java/com/hrbank/service/BackupService.java, src/main/java/com/hrbank/service/basic/BasicBackupService.java
ex) feature/15-backup-csv-scheduler -> main
- close #15 
- 백업 목록 조회 기능 구현 (`searchBackups`)  
- 다중 조건 필터링: `worker`, `status`, `from`, `to`  
- 정렬 필드 및 방향: `startedAt`, `endedAt`, `ASC`/`DESC` 지원  
- 커서 기반 페이지네이션 적용 (`cursor`, `nextCursor`, `nextIdAfter`)  
- `size` 파라미터의 기본값 10 처리  
- 커서 인코딩/디코딩 헬퍼 함수 추가  
- `encodeCursor(Long id)` – `{"id": <id>}` → Base64 인코딩  
- `decodeCursor(String cursor)` – Base64 디코딩 후 JSON 파싱  
- 백업 스케줄러 등록 (`BackupScheduler`)  
- `@Scheduled(cron = "0 0 * * * *")`로 매 시간 정각마다 자동 실행  
- 시스템 요청자 `"system"`으로 `runBackup("system")` 호출
=> [#15} 커서 기반 페이징 구현 + 스케쥴러 등록

src/main/java/com/hrbank/controller/BackupController.java, src/main/java/com/hrbank/service/BackupService.java, src/main/java/com/hrbank/service/basic/BasicBackupService.java
ex) feature/36-backup-api-> main
- close #36 
- 백업 API (`BackupController`) 개발
- GET `/api/backups`  
- 커서 기반 페이징 및 필터링(작업자, 상태, 시작일 등) 지원하는 백업 목록 조회 API 구현
- POST `/api/backups`  
- 백업 실행 API 구현 (`runBackup` 호출)  
- 요청자 IP 기반으로 작업 기록 생성 및 결과 응답
- GET `/api/backups/latest`  
- 상태별 최신 백업 1건 조회 API 구현 (`COMPLETED`, `FAILED` 등)
- 백업 서비스 (`BasicBackupService`) 개선
- `runBackup(String requesterIp)`  
- 반환 타입 `void` → `BackupDto`로 변경하여 API 응답 가능하도록 개선
- `markBackupCompleted`, `markBackupFailed`, `createInProgressBackup` , 'isBackupRequired'
- 외부 호출 불필요한 메서드는 `private`으로 접근 제어 변경 (캡슐화 강화)
- `searchBackups()` 내 기본값 처리 제거  
- `size` 기본값을 컨트롤러에서 `@RequestParam(defaultValue = "10")`으로 일원화
- 트랜잭션 선언
- 외부 호출 메서드에만 `@Transactional` 선언
=> [#36] 백업 API 구현 및 서비스 개선

src/main/java/com/hrbank/controller/EmployeeController.java, src/main/java/com/hrbank/dto/employee/EmployeeUpdateRequest.java, src/main/java/com/hrbank/entity/Employee.java, src/main/java/com/hrbank/service/EmployeeService.java, src/main/java/com/hrbank/service/basic/BasicEmployeeService.java
feature/27-update-employee-v2 -> main
- close #27 
- 직원 정보 수정 API 컨트롤러 추가
- 수정 요청을 처리하기 위한 서비스 로직 구현
- 존재하지 않는 직원 또는 부서에 대한 예외 처리 추가
- 예외 발생시 RestException 방식으로 처리 (머지되면 Enum에 추가 예정)
=> [#27] 직원 정보 수정 API 구현

src/main/java/com/hrbank/controller/BackupController.java, src/main/java/com/hrbank/controller/api/BackupApi.java, src/main/java/com/hrbank/dto/backup/BackupDto.java, src/main/java/com/hrbank/entity/Backup.java, src/main/java/com/hrbank/exception/ErrorCode.java, src/main/java/com/hrbank/repository/BackupRepository.java, src/main/java/com/hrbank/service/BackupService.java, src/main/java/com/hrbank/service/basic/BasicBackupService.java
ex) feature/39-backup-exception-handler-> main
- close #39 
- **refactor: Instant → LocalDateTime으로 시간 타입 변경**
- API 요청 및 서비스 로직에서 `Instant` 대신 `LocalDateTime` 사용
- 시간대 의존성 제거 및 Swagger 문서에 ISO 포맷 적용
- **refactor: @RequestParam에서 중복된 required 속성 제거**
- `defaultValue`가 지정된 파라미터에 `required = false` 제거하여 코드 간결화
- **feat: 백업 진행 중 상태 감지 시 409 Conflict 에러 처리 추가**
- `IN_PROGRESS` 상태의 백업이 존재할 경우 409 에러 반환
- 중복 실행 방지를 위한 예외 처리 추가
- **feat: 백업 도메인 에러 코드 정의 및 서비스 로직 적용**
- ErrorCode 항목 추가:
- `BACKUP_NOT_FOUND`
- `BACKUP_LATEST_NOT_FOUND`
- `BACKUP_CSV_NOT_FOUND`
- `BACKUP_ERROR_LOG_NOT_FOUND`
- `BACKUP_ALREADY_IN_PROGRESS`
- 각 상황에 맞는 예외를 서비스 내에 적용
- **docs: Swagger 문서용 BackupApi 인터페이스 정리*
- Swagger 문서 전용 `BackupApi` 인터페이스 분리
- `@Parameter` + `@Schema(defaultValue = "...")` 조합으로 문서 명확화
=> [#39] 백업 기능 에외 전역처리 및 Swagger 명세

src/main/java/com/hrbank/controller/EmployeeController.java, src/main/java/com/hrbank/exception/ErrorCode.java, src/main/java/com/hrbank/mapper/BinaryContentMapper.java, src/main/java/com/hrbank/mapper/EmployeeMapper.java, src/main/java/com/hrbank/service/BinaryContentService.java, src/main/java/com/hrbank/service/EmployeeService.java, src/main/java/com/hrbank/service/basic/BasicBinaryContentService.java, src/main/java/com/hrbank/service/basic/BasicEmployeeService.java, src/main/java/com/hrbank/storage/BinaryContentStorage.java
ex) feature/34-employee-delete
- close #34 
- 직원 삭제 API: delete 메서드를 EmployeeService와 BasicEmployeeService에 추가하여, 직원 삭제 시 프로필 이미지도 삭제하도록 구현.
- update 메서드 수정: 이메일 중복 체크 및 기존 프로필 이미지 삭제 후 새 이미지로 변경.
- 타입 수정: BinaryContentDto 대신 BinaryContent를 사용하여 타입 오류 해결.
- 변경 전 상태 보존: changeLogService를 사용하여 직원 정보 변경 이력을 로그로 저장.
=> [#34] 직원 API 구현 및 기존 코드 수정 작업

src/main/java/com/hrbank/service/basic/BasicBinaryContentService.java
ex) 34-employee-delete-fix -> main
- close #34 
- BinaryContent 객체에만 집중하여 삭제 처리 (책임분리)
- 데이터베이스에서 삭제
리뷰 확인 받았고 바로 머지하도록 하겠습니다.
=> [#34] BasicBinaryContentService delete 책임분리 재설정

src/main/java/com/hrbank/repository/specification/EmployeeChangeLogSpecification.java
feature/100-specification-enum-fix -> main
- close #100
- `EmployeeChangeLogSpecification.typeEquals` 메서드 내 enum 비교 조건을 `cb.equal(root.get("type"), cb.literal(type))` 방식으로 수정하였습니다.
- PostgreSQL에서는 enum과 문자열 간 비교가 허용되지 않아, 이전 코드(`cb.equal(root.get("type"), type)`)로는 실행 오류가 발생했습니다.
=> [#100] PostgreSQL ENUM 타입 호환을 위한 cb.literal 적용

src/main/java/com/hrbank/entity/Backup.java, src/main/java/com/hrbank/repository/EmployeeRepository.java, src/main/java/com/hrbank/service/basic/BasicBackupService.java
ex) fix/98-immutablelist-collect) -> main
- close #98 
- stream().toList() 사용 시 ImmutableList가 생성되어 sort() 호출 시 UnsupportedOperationException이 발생하던 문제를 수정했습니다.
- toList() 대신 collect(Collectors.toList())를 사용하여 변경 가능한 리스트를 생성하고, 정상적으로 정렬이 가능하도록 수정했습니다.
- employeeRepository에 existsBy 메서드를 추가하여 직원 데이터가 하나도 없을 경우 백업을 수행하지 않도록 로직을 수정했습니다.
- 최초 백업 시에도 직원 데이터 존재 여부를 먼저 확인하여 불필요한 백업을 방지했습니다.
- findTopByStatusOrderByEndedAtDesc 호출 시, 백업 데이터가 없을 경우 예외를 던지지 않고 null을 반환하도록 수정했습니다.
=> [#98] 백업 필요성 판단 로직 개선 및 최신 백업 조회 방식 수정

src/main/java/com/hrbank/entity/Backup.java, src/main/java/com/hrbank/repository/EmployeeRepository.java, src/main/java/com/hrbank/service/basic/BasicBackupService.java
fix/98-immutablelist-collect) -> main
- close #98 
- PR #112 
PR #112  를 merge하였음에도 main에 반영이 되지않아 다시 올립니다.
- stream().toList() 사용 시 ImmutableList가 생성되어 sort() 호출 시 UnsupportedOperationException이 발생하던 문제를 수정했습니다.
- toList() 대신 collect(Collectors.toList())를 사용하여 변경 가능한 리스트를 생성하고, 정상적으로 정렬이 가능하도록 수정했습니다.
- employeeRepository에 existsBy 메서드를 추가하여 직원 데이터가 하나도 없을 경우 백업을 수행하지 않도록 로직을 수정했습니다.
- 최초 백업 시에도 직원 데이터 존재 여부를 먼저 확인하여 불필요한 백업을 방지했습니다.
- findTopByStatusOrderByEndedAtDesc 호출 시, 백업 데이터가 없을 경우 예외를 던지지 않고 null을 반환하도록 수정했습니다.
=> [#98] PR#112 merge오류로 인해 재업로드

src/main/java/com/hrbank/controller/EmployeeController.java, src/main/java/com/hrbank/dto/employee/EmployeeTrendDto.java, src/main/java/com/hrbank/repository/EmployeeRepository.java, src/main/java/com/hrbank/repository/EmployeeRepositoryCustom.java, src/main/java/com/hrbank/repository/EmployeeRepositoryImpl.java, src/main/java/com/hrbank/service/EmployeeService.java, src/main/java/com/hrbank/service/basic/BasicEmployeeService.java
fix/120-employee-trend -> main
- close #120 
- 직원 수 추이 조회 API (`/api/employees/stats/trend`)의 입력 파라미터를 변경했습니다.
- `EmployeeSearchCondition` + `Pageable` → `@RequestParam` 방식(`from`, `to`, `unit`)으로 수정
- 기본 반환 타입을 `Page<EmployeeTrendDto>` → `List<EmployeeTrendDto>`로 변경했습니다.
- 서비스 로직(`findEmployeeTrends`)에서 Pageable 관련 로직 제거하고, List만 반환하도록 수정했습니다.
- JPQL 쿼리문에서 H2 데이터베이스 호환을 위해 `FORMATDATETIME` 대신 `TO_CHAR` 함수 사용하도록 수정했습니다.
=> [#120] 직원 수 추이 조회 API 파라미터 방식 변경 및 리턴 타입 수정

src/main/java/com/hrbank/repository/EmployeeRepository.java, src/main/java/com/hrbank/service/basic/BasicEmployeeChangeLogService.java, src/main/java/com/hrbank/service/basic/BasicEmployeeService.java
ex) fix/bug-> main
- close 
<직원 관리>
- 생성/수정/삭제 시 수정 이력 저장때문에 항상 부서의 이름, 이미지의 파일이름을 가져와야 함 => N+1문제가 있을 수 있기에, N+1문제를 방지하고자 fetch join을 사용해 Department 데이터와 BinaryContent 데이터를 힌 번에 가져옴. 
- 직원 삭제 시 before(직원 객체)에 BinaryContent객체를 안 넣어주기에 바꿈. 
<직원 수정 이력 관리 - saveChangeLog()>
- 기존엔 직원을 수정하였을 때만 상세 이력을 저장하였음. 하지만 프로토타입을 보니, 생성/삭제일 때도 저장이 되기에 이를 추가해줌.
- 삭제일 땐, 사번을 보여주지 않기에, 삭제일 경우 사번은 제외시켜주었음.
- 수정 - 상세 이력 순서를 프로토타입과 동일하게 변경 & 입사일 이력 저장되도록 추가
- 직원이 생성될 경우
- 삭제될 경우
=> [직원수정이력] 직원 생성/삭제 일 때도 상세 내역 저장

src/main/java/com/hrbank/generator/EmployeeCsvGenerator.java, src/main/java/com/hrbank/service/basic/BasicBackupService.java
ex) fix/135-backup-file-name -> main
- close #135 
- 기존 .csv 파일의 이름은 임시 파일을 만들기 위해 사용하였던 createTempFile때문에 랜덤값이 붙었음. 이를 해결하기 위해 파일 이름을 임시 파일 생성 후 따로 생성하여 저장함. 
- .log 파일이름은 날짜가 붙지 않아, 날짜와 시간까지 포함되게끔 변경.
=> [#135] backup 파일 이름 변경

src/main/java/com/hrbank/controller/EmployeeChangeLogController.java, src/main/java/com/hrbank/dto/employeeChangeLog/EmployeeChangeLogSearchRequest.java, src/main/java/com/hrbank/repository/specification/EmployeeChangeLogSpecification.java, src/main/java/com/hrbank/service/EmployeeChangeLogService.java, src/main/java/com/hrbank/service/basic/BasicEmployeeChangeLogService.java
feature/143-change-logs-datetime-to-offsetdatetime -> main
- close #143
- EmployeeChangeLogSearchRequest의 atFrom, atTo 필드를 LocalDateTime → OffsetDateTime으로 변경
- atBetween 스펙 메서드가 OffsetDateTime을 받도록 수정하고 내부에서 LocalDateTime으로 변환
- Service와 Controller 모두 OffsetDateTime을 사용하도록 수정
- 프론트엔드에서 Z(UTC)가 포함된 ISO 8601 포맷 날짜를 정상적으로 받을 수 있도록 수정
시작일/종료일을 선택하여도 정상 작동
=> [#143] 변경 이력 날짜 필드를 LocalDateTime에서 OffsetDateTime으로 변경

src/main/java/com/hrbank/dto/employee/EmployeeTrendDto.java, src/main/java/com/hrbank/generator/EmployeeCsvGenerator.java, src/main/java/com/hrbank/repository/EmployeeRepositoryImpl.java, src/main/java/com/hrbank/service/basic/BasicBackupService.java
ex) fix/138-employees-trend-fix -> main
- close #138 
- from이 null이었을 때, unit을 기준으로 총 13개의 EmployeeTrendDto가 생성되도록 변경.
- ✅ 실수로 main에서 브랜치를 생성하지 않아 다른 브랜치에서 변경한 이력이 포함되어있습니다. EmployeeRepositoryImpl와 EmployeeTrendDto만 확인해주세요.
- 월별 직원 수 추이 결과
- 분기별 직원 수 추이 결과
나머지도 잘 실행됩니답
=> [#138] 직원 수 추이 조회 수정

src/main/java/com/hrbank/entity/Backup.java, src/main/java/com/hrbank/service/basic/BasicBackupService.java
refactor/137-backup-lazy-transaction -> main
- close #137 
- BasicBackupService 클래스 레벨 @Transactional 제거
- 조회 메서드에 @Transactional(readOnly = true) 적용
- 쓰기 메서드에 @Transactional 적용
- Backup 엔티티의 file 연관관계 FetchType.LAZY 적용
- 필요할 때만 BinaryContent 조회
- 리스트 조회 성능 최적화 및 N+1 문제 방지
=> [#137] 백업 N+1 예방 및 트랜젝션 설정

src/main/java/com/hrbank/controller/EmployeeChangeLogController.java, src/main/java/com/hrbank/controller/api/EmployeeChangeLogControllerApi.java, src/main/java/com/hrbank/dto/employeeChangeLog/EmployeeChangeLogSearchRequest.java, src/main/java/com/hrbank/service/EmployeeChangeLogService.java, src/main/java/com/hrbank/service/basic/BasicEmployeeChangeLogService.java
feature/155-add-employee-change-log-api-docs -> main
- close #155
- API 요청 파라미터와 응답 스펙을 Swagger UI에 명확히 표시
- 사용하지 않는 hasChangeSince 메서드 제거
=> [#155] EmployeeChangeLogController API 명세(Swagger) 추가 및 정리

src/main/java/com/hrbank/mapper/EmployeeMapper.java
fix/employee-mapper-departmentid-mapping-pull -> main
- close #이슈 번호
- `@Mapping(source = "department.id", target = "departmentId")` 어노테이션을 추가하여 누락된 매핑을 보완했습니다.
- 해당 수정으로 컴파일 경고 및 충돌 문제를 해결했습니다.
=> fix: EmployeeMapper에서 departmentId 매핑 누락 수정(재업로드)

src/main/java/com/hrbank/controller/FrontendController.java, src/main/resources/application.yml
main -> main
- application.yml 파일에 서버 포트(port) 설정 추가 (`server.port: ${PORT:8080}`)
- FrontendController 추가하여 SPA(Single Page Application) 경로 새로고침 및 직접 접근 시 정상적으로 index.html 반환 처리
- 기존에는 /departments, /employees 등 경로를 직접 입력하거나 새로고침하면 서버가 정적 파일을 찾으려고 하면서 500 에러가 발생했습니다.
- 이를 해결하기 위해 FrontendController를 추가하여, 주요 프론트 경로 요청은 index.html로 포워딩하고 이후 프론트엔드 라우터가 경로를 해석하도록 변경했습니다.
- 추가로 application.yml 파일에 server.port를 환경변수 기반으로 설정하여 Railway와 같은 배포 환경에서도 포트 지정이 가능하도록 수정했습니다.
- 기능상 변경은 없으며, 초기 진입 및 경로 이동 안정성 향상을 위한 설정입니다.
=> feat: 서버 포트 설정 추가 및 FrontendController 추가로 SPA 경로 대응
