- src/main/java/com/hrbank/dto/department/CursorPageResponseDepartmentDto.java
- src/main/java/com/hrbank/dto/department/DepartmentCreateRequest.java
- src/main/java/com/hrbank/dto/department/DepartmentDto.java
- src/main/java/com/hrbank/dto/department/DepartmentUpdateRequest.java
- src/main/java/com/hrbank/entity/Department.java
- src/main/java/com/hrbank/mapper/DepartmentMapper.java
- src/main/java/com/hrbank/repository/DepartmentRepository.java
- src/main/java/com/hrbank/service/DepartmentService.java
- src/main/java/com/hrbank/service/basic/BasicDepartmentService.java
- src/main/resources/application.properties
feat/4-department -> main
- 부서 관리 기능을 위한 핵심 도메인 department 정의
- departmentRepository(JpaRepository상속) 생성
- DepartmentService인터페이스, DepartmentService클래스 생성
Closes #4
> [#4] 부서 관리 기능 도메인 설계 및 기본 기능 구현

- src/main/java/com/hrbank/controller/EmployeeController.java
- src/main/java/com/hrbank/dto/employee/CursorPageResponseEmployeeDto.java
- src/main/java/com/hrbank/dto/employee/EmployeeDto.java
- src/main/java/com/hrbank/dto/employee/EmployeeSearchCondition.java
- src/main/java/com/hrbank/entity/Employee.java
- src/main/java/com/hrbank/enums/EmployeeStatus.java
- src/main/java/com/hrbank/mapper/EmployeeMapper.java
- src/main/java/com/hrbank/repository/EmployeeRepository.java
- src/main/java/com/hrbank/repository/EmployeeRepositoryCustom.java
- src/main/java/com/hrbank/repository/EmployeeRepositoryImpl.java
- src/main/java/com/hrbank/service/EmployeeService.java
- src/main/java/com/hrbank/service/basic/BasicEmployeeService.java
ex) feature/5-employee-list -> main
- close #5 
- 직원 목록 조회 기능을 구현했습니다.
- 커서 기반 페이지네이션 방식으로, name/email/부서/입사일 등 다양한 필터 조건을 통해 조회 가능합니다.
- Swagger API 명세서 기반으로 컨트롤러 구성 완료했습니다.
> [#5] 직원 목록 조회 기능 구현

- src/main/java/com/hrbank/dto/backup/BackupDto.java
- src/main/java/com/hrbank/dto/backup/CursorPageResponseBackupDto.java
- src/main/java/com/hrbank/entity/Backup.java
- src/main/java/com/hrbank/enums/BackupStatus.java
- src/main/java/com/hrbank/mapper/BackupMapper.java
- src/main/java/com/hrbank/repository/BackupRepository.java
- src/main/java/com/hrbank/service/BackupService.java
- src/main/java/com/hrbank/service/basic/BasicBackupService.java
ex) feat/login -> dev
- close #8 
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
ex) "베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 
결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다."
> [#8] 백업 기능 관련 도메인및 기능 구현(revert후 재업로드)

- src/main/java/com/hrbank/controller/DepartmentController.java
- src/main/java/com/hrbank/controller/api/DepartmentApi.java
- src/main/java/com/hrbank/dto/department/CursorPageResponseDepartmentDto.java
- src/main/java/com/hrbank/dto/department/DepartmentDto.java
- src/main/java/com/hrbank/entity/Department.java
- src/main/java/com/hrbank/mapper/DepartmentMapper.java
- src/main/java/com/hrbank/repository/DepartmentRepository.java
- src/main/java/com/hrbank/service/DepartmentService.java
- src/main/java/com/hrbank/service/basic/BasicDepartmentService.java
ex) feat/18-department-api -> main
- close #18 
- 명시된 api 명세서에 호환되도록 기존 코드 수정
- departmentApi 구현
- departmentController 구현
> [#18] 부서 관리 기능 API 구현

- src/main/java/com/hrbank/dto/error/ErrorResponse.java
- src/main/java/com/hrbank/exception/GlobalExceptionHandler.java
- src/main/java/com/hrbank/exception/RestException.java
- src/main/java/com/hrbank/service/basic/BasicDepartmentService.java
ex) feat/35-department-GlobalException -> main
- close #35 
- 예외 처리 관련 RestException, GlobalExceptionHandler, ErrorResponse 도입했습니다.
- 멘토님이 말씀해주셨던 로깅 처리를 위한 @Slf4j 어노테이션 추가했습니다.
> [#35] 부서 관리 기능 전역 예외 처리

- src/main/java/com/hrbank/dto/error/ErrorResponse.java
- src/main/java/com/hrbank/exception/ErrorCode.java
- src/main/java/com/hrbank/exception/RestException.java
- src/main/java/com/hrbank/service/basic/BasicDepartmentService.java
ex) feat/43-resolveError-MergeConflict -> main
- close #43 
- 병합 후 생긴 에러코드 클래스로 인한 오류 해결 및 에러코드 클래스 세부 항목 추가
> [#43] 병합 충돌 해결 이후 생긴 오류 해결

- src/main/java/com/hrbank/controller/DepartmentController.java
- src/main/java/com/hrbank/exception/ErrorCode.java
- src/main/java/com/hrbank/repository/DepartmentRepository.java
- src/main/java/com/hrbank/repository/specification/DepartmentSpecifications.java
- src/main/java/com/hrbank/service/basic/BasicDepartmentService.java
feature/57-fixBug-refactor
- close #57 
- 에러코드에 불필요하게 생긴 ;제거
- specifation 클래스 도입 및 controller단 defaultValue 사용으로 인한 required = false 삭제
> [#57] 코드 병합으로 인한 오류 해결과 코드 개선

- src/main/java/com/hrbank/controller/EmployeeController.java
- src/main/java/com/hrbank/service/EmployeeService.java
- src/main/java/com/hrbank/service/basic/BasicEmployeeService.java
ex) feature/55-employee-detail -> main 
- close #55 
- 직원 정보를 id로 조회하여 직원 상세 정보를 반환합니다. 
- 직원이 없을 경우 예외를 던집니다.
> [#55] 직원 상세 조회 API 구현

- src/main/java/com/hrbank/mapper/DepartmentMapper.java
- src/main/java/com/hrbank/repository/DepartmentRepository.java
- src/main/java/com/hrbank/repository/specification/DepartmentSpecifications.java
- src/main/java/com/hrbank/service/basic/BasicDepartmentService.java
feat/68-refactor-presentCode -> main
- close #68 
- 더 이상 사용하지 않는 메서드 삭제.
- 커서 기반 페이지네이션 구현.
- 지연 로딩으로 인해 발생한 N+1문제 해결.
> [#68] 커서 기반 페이지네이션, N+1문제 해결

- src/main/java/com/hrbank/entity/Department.java
feat/76-refactor-departmentEntity -> main
- close #76 
누락됐던 description, establishedDate nullable = false 추가했습니다.
> [#76] 부서 관리 도메인 설명, 설립일 제약조건 추가

- src/main/java/com/hrbank/controller/EmployeeController.java
- src/main/java/com/hrbank/dto/employee/CursorPageResponseEmployeeDto.java
- src/main/java/com/hrbank/dto/employee/EmployeeDto.java
- src/main/java/com/hrbank/dto/employee/EmployeeSearchCondition.java
- src/main/java/com/hrbank/entity/Employee.java
- src/main/java/com/hrbank/mapper/EmployeeMapper.java
- src/main/java/com/hrbank/repository/EmployeeRepository.java
- src/main/java/com/hrbank/repository/EmployeeRepositoryCustom.java
- src/main/java/com/hrbank/repository/EmployeeRepositoryImpl.java
- src/main/java/com/hrbank/service/EmployeeService.java
- src/main/java/com/hrbank/service/basic/BasicEmployeeService.java
ex) 71-refactoring -> main
- close #71 
- 직원 상세 조회 profileImageId 누락 확인하였습니다. API 명세서에 맞게 변경
- 직원 목록 조회 페이징 네이션 구현했습니다.
> [#71] 직원상세정보 profileId 누락 추가 및 직원목록 조회 페이징네이션 구현

- src/main/java/com/hrbank/controller/EmployeeController.java
- src/main/java/com/hrbank/service/EmployeeService.java
- src/main/java/com/hrbank/service/basic/BasicEmployeeService.java
ex) 71-add-saveChangeLog
- close #71 
- 직원이 생성/수정/삭제 될 때 saveChangeLog 가 호출이 되도록 구현
ex) "베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 
결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다."
> [#71] saveChangeLog 구현

- src/main/java/com/hrbank/entity/EmployeeChangeLog.java
- src/main/java/com/hrbank/entity/EmployeeChangeLogDetail.java
ex )feature/87-add-not-null-constraints -> dev
- close #87
change_logs 및 change_log_diffs 테이블에 NOT NULL 제약 추가
> [#87] change_logs 및 change_log_diffs 테이블 필수 컬럼에 NOT NULL 제약 추가

- src/main/java/com/hrbank/entity/EmployeeChangeLog.java
ex) feature/90-fix-entity -> dev
- close #90
데이터베이스와 클래스의 필드를 매핑시키기 위해 EnployeeChangeLog.java 코드를 수정했습니다.
> [#90] 데이터베이스와 이름이 같도록 columDefinition 설정 추가

- src/main/java/com/hrbank/controller/EmployeeController.java
- src/main/java/com/hrbank/dto/employee/EmployeeDistributionDto.java
- src/main/java/com/hrbank/repository/EmployeeRepository.java
- src/main/java/com/hrbank/service/EmployeeService.java
- src/main/java/com/hrbank/service/basic/BasicEmployeeService.java
feature/95-employeeDistribution -> main
- close #95 
- 직원 분포 조회를 위한 dto 추가했습니다.
- api 명세에 맞게 controller 추가사항 있습니다.
- 부서별, 상태별 직원 분포 조회하는 쿼리 추가했습니다.
- 그에 맞는 서비스단 추가했습니다.
> [#95] 직원 분포 조회 관련 개발

- src/main/java/com/hrbank/repository/specification/EmployeeChangeLogSpecification.java
revert/106-spec-enum-literal-to-varchar -> main
- close #106
104번 이슈의 수정사항이 정상적으로 적용되지 않아 재차 적용하였습니다.
- EmployeeChageLogDetail.java에서 enum 비교 방식 제거 후 기존 방식으로 복원
> [#106] 누락된 수정사항 추가

- src/main/java/com/hrbank/controller/EmployeeController.java
- src/main/java/com/hrbank/repository/EmployeeRepository.java
- src/main/java/com/hrbank/service/EmployeeService.java
- src/main/java/com/hrbank/service/basic/BasicEmployeeService.java
108-employee-count -> main
- close #108 
- 직원 상태별 집계, 입사일 기간 필터링 파라미터 지원
- 파라미터 미지정시 전체 직원 수 반환
ex) "베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 
결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다."
> [#108] 직원 수 대시보드 조회 API 구현

- src/main/java/com/hrbank/repository/EmployeeRepository.java
ex) patch-localDate
EmployeeRepo LocalDate 임포트 클래스 누락 추가하였습니다.
> 긴급 fix: localDate 임포트 클래스 누락

- src/main/java/com/hrbank/controller/EmployeeController.java
- src/main/java/com/hrbank/service/basic/BasicEmployeeService.java
fix-employee-1 -> main 
- create 할때 불필요한 before 객체 생성 없이 바로 Null 로 넘겨주었습니다. 
- createEmployee 파트 parameter 변수명 수정했습니다. 
정상적으로 동작합니다.
> fix: 피어 리뷰 반영(createEmployee profile 파라미터 이름, before->null 처리)

- src/main/java/com/hrbank/entity/Department.java
- src/main/java/com/hrbank/entity/Employee.java
feature/126-bugFix -> main
- close #126 
초기 도메인 설계에서 두 엔티티 모두 서로 참조하고있어 양방향 관계 -> department entity수정
> [#126] 참조관계 수정

- src/main/java/com/hrbank/repository/specification/BackupSpecifications.java
chore/128-add-BackupSpecifications -> main
- close #128 
누락된 BackupSpecifications 추가 하였습니다
> 누락된 BackupSpecifications 추가

- src/main/java/com/hrbank/controller/EmployeeController.java
- src/main/java/com/hrbank/dto/employee/EmployeeCreateRequest.java
- src/main/java/com/hrbank/entity/Backup.java
- src/main/java/com/hrbank/entity/BinaryContent.java
- src/main/java/com/hrbank/entity/Department.java
- src/main/java/com/hrbank/entity/EmployeeChangeLog.java
- src/main/java/com/hrbank/entity/EmployeeChangeLogDetail.java
- src/main/java/com/hrbank/service/EmployeeService.java
- src/main/java/com/hrbank/service/basic/BasicBinaryContentService.java
- src/main/java/com/hrbank/service/basic/BasicEmployeeService.java
- src/main/java/com/hrbank/storage/BinaryContentStorage.java
ex) fix/create-update-fix -> main 
- close #이슈 번호
- 머지 오류인지 @GeneratedValue(strategy = GenerationType.IDENTITY)가 안 바뀌어서 다시 바꿈.
- (BasicEmployeeService) update:
-> 이메일 중복 체크: 기존 이메일과 같을 경우엔 중복 체크하지 않도록 변경
-> 새로 들어온 프로필이 있을 때 기존 BinaryContent삭제 후 새로운 이미지 등록
-> 모든 변경 후에 save() 호출하여 DB에 반영
- 실제 이미지 파일 저장할 때, 확장자를 넣지 않으니 파일 구분이 어렵고, get()에 문제가 생겨 ex) image.png처럼 확장자까지 fileName에 포함시킴.
- 이미지 파일 이름이 한글일 때도 문제없이 다운로드되도록 설정.
문제없이 등록/수정/삭제 가능
> employee의 등록/수정 문제 해결과 이미지 파일 저장/삭제 문제 해결

- src/main/java/com/hrbank/entity/Department.java
- src/main/java/com/hrbank/mapper/DepartmentMapper.java
- src/main/java/com/hrbank/repository/DepartmentRepository.java
- src/main/java/com/hrbank/service/basic/BasicDepartmentService.java
feature/133-chore-departments -> main
- close #133 
- 기존 양방향 맵핑 -> 단방향으로 변경되면서 존재하던 N+1 문제가 사라졌으나 직원 수 조회 로직은 여전히 비즈니스 로직으로 필요해 주석만 변경
- 불필요한 import문 삭제
> [#133] chore: 부서 관리 주석 변경

- src/main/java/com/hrbank/dto/employee/EmployeeSearchCondition.java
- src/main/java/com/hrbank/repository/EmployeeRepositoryImpl.java
141-fix-employee-search-filter -> main
- close #141 
- findAllWIthFilter 에 이름 또는 이메일 검색 조건 쿼리가 없어서 안되었던 현상 해결
> [#141] 직원 목록 필터 안되는 이슈 해결

- src/main/java/com/hrbank/Sb02HrbankTeam5Application.java
- src/main/java/com/hrbank/entity/Backup.java
- src/main/java/com/hrbank/service/basic/BasicBackupService.java
feature/146-backup-scheduler -> main
- close #146 
- @EnableScheduling 어노테이션을 추가하여 스케줄링 기능을 활성화함
> [#146] 스케줄링 기능 활성화

- src/main/java/com/hrbank/controller/BackupController.java
- src/main/java/com/hrbank/controller/EmployeeChangeLogController.java
- src/main/java/com/hrbank/controller/api/BackupApi.java
- src/main/java/com/hrbank/dto/backup/BackupDto.java
- src/main/java/com/hrbank/entity/Backup.java
- src/main/java/com/hrbank/repository/EmployeeChangeLogRepository.java
- src/main/java/com/hrbank/repository/specification/BackupSpecifications.java
- src/main/java/com/hrbank/service/BackupService.java
- src/main/java/com/hrbank/service/EmployeeChangeLogService.java
- src/main/java/com/hrbank/service/basic/BasicBackupService.java
- src/main/java/com/hrbank/service/basic/BasicEmployeeChangeLogService.java
fix/149-filtering-bug -> main
- close #149 
- 기존 LocalDateTime 사용 부분을 OffsetDateTime으로 변경했습니다.
- 시간대(UTC/KST) 정보를 정확히 관리하기 위해 수정되었습니다.
- Entity, Repository, Service 레이어 모두 일관되게 변경했습니다.
- 데이터베이스 timestamp with time zone 타입으로 변경했습니다.
> [#149] 백업 필터링 오류 수정

- src/main/java/com/hrbank/mapper/EmployeeChangeLogMapper.java
feature/153-translate-status-in-diffs -> main
- close #153
상태(status) 값 (ACTIVE, ON_LEAVE, RESIGNED)을 한글 (재직중, 휴직중, 퇴사)으로 변환하여 응답
> [#153] 이력 변경 상세 조회 API에서 상태(status) 값을 한글로 변환하여 응답

- src/main/java/com/hrbank/controller/api/DepartmentApi.java
fix/159-errormessage
- close #159 
api오류 예시 변경했습니다.
> [#159] 부서 관리 에러 예시 추가

- src/main/java/com/hrbank/controller/api/BinaryContentApi.java
- src/main/java/com/hrbank/dto/error/ErrorResponse.java
ex) fix/error-api-example -> main
- close #이슈 번호
저희 프로젝트에서 오류 발생했을 때, 위같이 나오길래, api 오류 예시도 위처럼 변경하였습니다.
> api 에러 예시 추가 + binaryContent API에 에러 예시 추가

- src/main/java/com/hrbank/controller/api/EmployeeChangeLogControllerApi.java
refactor/162-update-count-change-logs-api-docs -> dev
- close #162
실제 구현 내용에 맞추어서 api 명세 내역 변경
> [#162] EmployeeChangeLogsController API 명세 수정

- src/main/resources/application.yml
- application.yml에서 DB 연결 정보를 환경변수로 대체
- 민감정보 하드코딩을 제거하고 안전한 배포 환경을 구성
refactor/separate-db-config-to-env -> main
- close #169 
- application.yml에서 DB 연결 정보를 환경변수로 대체
- 민감정보 하드코딩을 제거하고 안전한 배포 환경을 구성
- Railway 및 로컬 환경에서는 별도 환경변수 등록 필요
> : 환경변수로 DB 설정 분리
